/*
 * Copyright (C) 2026 aisleron.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.aisleron.ui.theme

import androidx.compose.ui.graphics.Color

// ============================================================================
// LIGHT MODE SYSTEM PRIMITIVES (From colors.xml)
// ============================================================================

// Standard Contrast Base
val LightPrimary = Color(0xFF0058BD)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF1E70E4)
val LightOnPrimaryContainer = Color(0xFFFEFCFF)
val LightSecondary = Color(0xFF485E8B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFB6CCFF)
val LightOnSecondaryContainer = Color(0xFF405682)
val LightTertiary = Color(0xFF8C34A3)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFA84FBE)
val LightOnTertiaryContainer = Color(0xFFFFFBFF)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightBackground = Color(0xFFF9F9FF)
val LightOnBackground = Color(0xFF191B23)
val LightSurface = Color(0xFFF9F9FF)
val LightOnSurface = Color(0xFF191B23)
val LightSurfaceVariant = Color(0xFFDEE2F2)
val LightOnSurfaceVariant = Color(0xFF424754)
val LightOutline = Color(0xFF727785)
val LightOutlineVariant = Color(0xFFC2C6D6)
val LightScrim = Color(0xFF000000)
val LightInverseSurface = Color(0xFF2E3038)
val LightInverseOnSurface = Color(0xFFEFF0FA)
val LightInversePrimary = Color(0xFFADC6FF)
val LightSurfaceDim = Color(0xFFD8D9E3)
val LightSurfaceBright = Color(0xFFF9F9FF)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF2F3FD)
val LightSurfaceContainer = Color(0xFFECEDF7)
val LightSurfaceContainerHigh = Color(0xFFE6E7F2)
val LightSurfaceContainerHighest = Color(0xFFE1E2EC)

// Medium Contrast Overlays
val LightPrimaryMedium = Color(0xFF003475)
val LightOnPrimaryMedium = Color(0xFFFFFFFF)
val LightPrimaryContainerMedium = Color(0xFF0A69DC)
val LightOnPrimaryContainerMedium = Color(0xFFFFFFFF)
val LightSecondaryMedium = Color(0xFF1E3560)
val LightOnSecondaryMedium = Color(0xFFFFFFFF)
val LightSecondaryContainerMedium = Color(0xFF576D9B)
val LightOnSecondaryContainerMedium = Color(0xFFFFFFFF)
val LightTertiaryMedium = Color(0xFF5F0075)
val LightOnTertiaryMedium = Color(0xFFFFFFFF)
val LightTertiaryContainerMedium = Color(0xFFA047B6)
val LightOnTertiaryContainerMedium = Color(0xFFFFFFFF)
val LightErrorMedium = Color(0xFF740006)
val LightOnErrorMedium = Color(0xFFFFFFFF)
val LightErrorContainerMedium = Color(0xFFCF2C27)
val LightOnErrorContainerMedium = Color(0xFFFFFFFF)
val LightBackgroundMedium = Color(0xFFF9F9FF)
val LightOnBackgroundMedium = Color(0xFF191B23)
val LightSurfaceMedium = Color(0xFFF9F9FF)
val LightOnSurfaceMedium = Color(0xFF0E1118)
val LightSurfaceVariantMedium = Color(0xFFDEE2F2)
val LightOnSurfaceVariantMedium = Color(0xFF313642)
val LightOutlineMedium = Color(0xFF4D5260)
val LightOutlineVariantMedium = Color(0xFF686D7B)
val LightSurfaceDimMedium = Color(0xFFD8D9E3)
val LightSurfaceBrightMedium = Color(0xFFF9F9FF)
val LightSurfaceContainerLowestMedium = Color(0xFFFFFFFF)
val LightSurfaceContainerLowMedium = Color(0xFFF2F3FD)
val LightSurfaceContainerMediumRes = Color(0xFFECEDF7)
val LightSurfaceContainerHighMedium = Color(0xFFE6E7F2)
val LightSurfaceContainerHighestMedium = Color(0xFFE1E2EC)

// High Contrast Overlays
val LightPrimaryHigh = Color(0xFF001A40)
val LightOnPrimaryHigh = Color(0xFFFFFFFF)
val LightPrimaryContainerHigh = Color(0xFF00499E)
val LightOnPrimaryContainerHigh = Color(0xFFFFFFFF)
val LightSecondaryHigh = Color(0xFF001B41)
val LightOnSecondaryHigh = Color(0xFFFFFFFF)
val LightSecondaryContainerHigh = Color(0xFF3B517D)
val LightOnSecondaryContainerHigh = Color(0xFFFFFFFF)
val LightTertiaryHigh = Color(0xFF380047)
val LightOnTertiaryHigh = Color(0xFFFFFFFF)
val LightTertiaryContainerHigh = Color(0xFF791C94)
val LightOnTertiaryContainerHigh = Color(0xFFFFFFFF)
val LightErrorHigh = Color(0xFF4E0002)
val LightOnErrorHigh = Color(0xFFFFFFFF)
val LightErrorContainerHigh = Color(0xFF93000A)
val LightOnErrorContainerHigh = Color(0xFFFFFFFF)
val LightBackgroundHigh = Color(0xFFF9F9FF)
val LightOnBackgroundHigh = Color(0xFF191B23)
val LightSurfaceHigh = Color(0xFFF9F9FF)
val LightOnSurfaceHigh = Color(0xFF000000)
val LightSurfaceVariantHigh = Color(0xFFDEE2F2)
val LightOnSurfaceVariantHigh = Color(0xFF131823)
val LightOutlineHigh = Color(0xFF2E323F)
val LightOutlineVariantHigh = Color(0xFF4B4F5C)
val LightSurfaceDimHigh = Color(0xFFB7B8C2)
val LightSurfaceBrightHigh = Color(0xFFF9F9FF)
val LightSurfaceContainerLowestHigh = Color(0xFFFFFFFF)
val LightSurfaceContainerLowHigh = Color(0xFFEFF0FA)
val LightSurfaceContainerHighRes = Color(0xFFE1E2EC)
val LightSurfaceContainerHighHigh = Color(0xFFD2D4DE)
val LightSurfaceContainerHighestHigh = Color(0xFFC4C6D0)

// ============================================================================
// DARK MODE SYSTEM PRIMITIVES (From colors-night.xml)
// ============================================================================

// Standard Contrast Base
val DarkPrimary = Color(0xFFFFB5A0)
val DarkOnPrimary = Color(0xFF5F1500)
val DarkPrimaryContainer = Color(0xFFFF5722)
val DarkOnPrimaryContainer = Color(0xFF541200)
val DarkSecondary = Color(0xFFFFB5A0)
val DarkOnSecondary = Color(0xFF5F1500)
val DarkSecondaryContainer = Color(0xFF7F2A10)
val DarkOnSecondaryContainer = Color(0xFFFF9B7E)
val DarkTertiary = Color(0xFFF2BF42)
val DarkOnTertiary = Color(0xFF3F2E00)
val DarkTertiaryContainer = Color(0xFFB78A00)
val DarkOnTertiaryContainer = Color(0xFF372700)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1E100C)
val DarkOnBackground = Color(0xFFFADCD4)
val DarkSurface = Color(0xFF1E100C)
val DarkOnSurface = Color(0xFFFADCD4)
val DarkSurfaceVariant = Color(0xFF5B4039)
val DarkOnSurfaceVariant = Color(0xFFE4BEB4)
val DarkOutline = Color(0xFFAB8980)
val DarkOutlineVariant = Color(0xFF5B4039)
val DarkScrim = Color(0xFF000000)
val DarkInverseSurface = Color(0xFFFADCD4)
val DarkInverseOnSurface = Color(0xFF3E2C27)
val DarkInversePrimary = Color(0xFFB02F00)
val DarkSurfaceDim = Color(0xFF1E100C)
val DarkSurfaceBright = Color(0xFF483530)
val DarkSurfaceContainerLowest = Color(0xFF180B07)
val DarkSurfaceContainerLow = Color(0xFF271813)
val DarkSurfaceContainer = Color(0xFF2C1C17)
val DarkSurfaceContainerHigh = Color(0xFF372621)
val DarkSurfaceContainerHighest = Color(0xFF43302B)

// Medium Contrast Overlays
val DarkPrimaryMedium = Color(0xFFFFD2C6)
val DarkOnPrimaryMedium = Color(0xFF4C0F00)
val DarkPrimaryContainerMedium = Color(0xFFFF5722)
val DarkOnPrimaryContainerMedium = Color(0xFF000000)
val DarkSecondaryMedium = Color(0xFFFFD2C6)
val DarkOnSecondaryMedium = Color(0xFF4C0F00)
val DarkSecondaryContainerMedium = Color(0xFFDF7151)
val DarkOnSecondaryContainerMedium = Color(0xFF000000)
val DarkTertiaryMedium = Color(0xFFFFD782)
val DarkOnTertiaryMedium = Color(0xFF322300)
val DarkTertiaryContainerMedium = Color(0xFFB78A00)
val DarkOnTertiaryContainerMedium = Color(0xFF000000)
val DarkErrorMedium = Color(0xFFFFD2CC)
val DarkOnErrorMedium = Color(0xFF540003)
val DarkErrorContainerMedium = Color(0xFFFF5449)
val DarkOnErrorContainerMedium = Color(0xFF000000)
val DarkBackgroundMedium = Color(0xFF1E100C)
val DarkOnBackgroundMedium = Color(0xFFFADCD4)
val DarkSurfaceMedium = Color(0xFF1E100C)
val DarkOnSurfaceMedium = Color(0xFFFFFFFF)
val DarkSurfaceVariantMedium = Color(0xFF5B4039)
val DarkOnSurfaceVariantMedium = Color(0xFFFBD4C9)
val DarkOutlineMedium = Color(0xFF1E100C)
val DarkOutlineVariantMedium = Color(0xFFAB897F)
val DarkSurfaceDimMedium = Color(0xFF1E100C)
val DarkSurfaceBrightMedium = Color(0xFF483530)
val DarkSurfaceContainerLowestMedium = Color(0xFF180B07)
val DarkSurfaceContainerLowMedium = Color(0xFF271813)
val DarkSurfaceContainerMediumRes = Color(0xFF2C1C17)
val DarkSurfaceContainerHighMedium = Color(0xFF372621)
val DarkSurfaceContainerHighestMedium = Color(0xFF43302B)

// High Contrast Overlays
val DarkPrimaryHigh = Color(0xFFFFF5F2)
val DarkOnPrimaryHigh = Color(0xFF000000)
val DarkPrimaryContainerHigh = Color(0xFFFFC0AE)
val DarkOnPrimaryContainerHigh = Color(0xFF000000)
val DarkSecondaryHigh = Color(0xFFFFF5F2)
val DarkOnSecondaryHigh = Color(0xFF000000)
val DarkSecondaryContainerHigh = Color(0xFFFFC0AE)
val DarkOnSecondaryContainerHigh = Color(0xFF000000)
val DarkTertiaryHigh = Color(0xFFFFF9EE)
val DarkOnTertiaryHigh = Color(0xFF000000)
val DarkTertiaryContainerHigh = Color(0xFFF2BF42)
val DarkOnTertiaryContainerHigh = Color(0xFF000000)
val DarkErrorHigh = Color(0xFFFFF5F4)
val DarkOnErrorHigh = Color(0xFF000000)
val DarkErrorContainerHigh = Color(0xFFFFB4AB)
val DarkOnErrorContainerHigh = Color(0xFF000000)
val DarkBackgroundHigh = Color(0xFF1E100C)
val DarkOnBackgroundHigh = Color(0xFFFFFFFF)
val DarkSurfaceHigh = Color(0xFF1E100C)
val DarkOnSurfaceHigh = Color(0xFFFFFFFF)
val DarkSurfaceVariantHigh = Color(0xFF5B4039)
val DarkOnSurfaceVariantHigh = Color(0xFFFFF5F2)
val DarkOutlineHigh = Color(0xFFFFF5F2)
val DarkOutlineVariantHigh = Color(0xFFCEAAA0)
val DarkSurfaceDimHigh = Color(0xFF1E100C)
val DarkSurfaceBrightHigh = Color(0xFF6F5650)
val DarkSurfaceContainerLowestHigh = Color(0xFF120603)
val DarkSurfaceContainerLowHigh = Color(0xFF22130F)
val DarkSurfaceContainerHighRes = Color(0xFF271813)
val DarkSurfaceContainerHighHigh = Color(0xFF32211D)
val DarkSurfaceContainerHighestHigh = Color(0xFF3D2C27)

// Custom App Color Mappings
val PureBlack = Color(0xFF000000)